---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ sshd_service }}"
    state: restarted

- name: restart_networkd
  service:
    name: systemd-networkd
    state: restarted

- name: restart_NetworkManager
  service:
    name: NetworkManager 
    state: restarted

- name: restart_resolved
  service:
    name: systemd-resolved
    state: restarted
