---
- hosts: all
  become: true
  connection: local
  tasks:
    - name: apt update
      apt: update_cache=yes
      when: ansible_facts['os_family']|lower == 'debian'
    - name: dnf update
      dnf: update_cache=yes
      when: ansible_facts['os_family']|lower == 'redhat'
