all:
  children:
    dataservers:
      hosts:
        192.168.100.103:
        Shindook:
      vars:
        ip_address: "192.168.100.103"
        mfsserver: "chunk"

    webservers:
      hosts:
        192.168.100.102:
        HP:
      vars:
        ip_address: "192.168.100.102"
        mfsserver: "main"

    workstations:
      hosts:
        192.168.100.101:
        Legion:
      vars:
        ip_address: "192.168.100.101"
        mfsserver: "chunk"

    devservers:
      hosts:
        dev:
      vars:
        ip_address: "192.168.100.101"
        mfsserver: "chunk"

  vars:
    branch: stream
