all:
  children:
    dataservers:
      hosts:
        192.168.100.100:
      vars:
        ip_address: "192.168.100.100"
        mfsserver: "chunk"

    webservers:
      hosts:
        192.168.100.102:
      vars:
        ip_address: "192.168.100.102"
        mfsserver: "main"

    workstations:
      hosts:
        192.168.100.101:
      vars:
        ip_address: "192.168.100.101"
        mfsserver: "chunk"

  vars:
    branch: stream
