all:
  children:
    dataservers:
      hosts:
        192.168.100.100:
        Shindook:
      vars:
        ip_address: "192.168.100.100"

    webservers:
      hosts:
        192.168.100.102:
        HP:
      vars:
        ip_address: "192.168.100.102"

    workstations:
      hosts:
        192.168.100.101:
        Legion:
      vars:
        ip_address: "192.168.100.101"

    devservers:
      hosts:
        dev:
      vars:
        ip_address: "192.168.100.101"

  vars:
    branch: stream
