##
## Setup a node with users, ssh, networking, ansible-pull etc.
##
## USAGE:
## sudo ansible-playbook -i hosts.yml pb-setup.yml
##

---

- hosts: localhost
  become: true
  connection: local

  vars:
    eth_device: enp0s8

  tasks:
    - name: debug
      debug:
        msg: "The IP is {{ ip_address }}"

  roles:
    - role: setup
