##
## Setup a node with users, ssh, networking, ansible-pull etc.
##
## USAGE:
## sudo ansible-playbook -i hosts.yml pb-setup.yml
##
---

- hosts: localhost
  become: true
  connection: local

  vars:
    # ip_address: 192.168.100.100
    # eth_device: enp0s8

  pre_tasks:
    - block:
      - debug: msg="IP address is {{ ip_address }}"
        when: eth_device is defined
      rescue:
        - fail:
            msg: >
              "IP address for the device '{{ eth_device }}' is not defined."
              "Please edit pb-setup.yml and set ip address first."

  roles:
    - role: setup
