---
- hosts: localhost
  become: true
  connection: local

  vars:
    ip_address: 192.168.100.101
    eth_device: enp0s8

  tasks:
    - name: debug
      debug:
        msg: "The IP is {{ ip_address }}"

  roles:
    - role: setup
