##
## Setup a node with users, ssh, networking etc.
##
## USAGE:
## sudo ansible-playbook pb-setup.yml
##
---

- hosts: all
  become: true
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ ansible_env.PATH }}"

  tasks:
    - include_role:
        name: setup

    - include_role:
        name: docker
      when: docker_needed == true

    - include_role:
        name: moosefs
