## USAGE:
## ansible-playbook playbook.yml
---

- hosts: all
  become: true
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ ansible_env.PATH }}"

  pre_tasks:
    - debug:
        msg: "host: {{ inventory_hostname }} ip: {{ ansible_host }}"
      tags: always

  tasks:
    - block:
        - include_role:
            name: setup
      tags: setup

    - block:
        - include_role:
            name: docker
      tags: docker
      when: docker_needed == true

    - block:
        - include_role:
            name: moosefs
      tags: moosefs
