version: "3"

services:
  namenode:
    image: akhlakm/hadoop-namenode
    container_name: namenode
    # restart: always
    ports:
      - 9870:9870
      - 9000:9000
    environment:
      - CLUSTER_NAME=Shindook
      - DOCKER_NETWORK=docker_hadoop

  datanode1:
    image: akhlakm/hadoop-datanode
    container_name: datanode1
    # restart: always
    environment:
      - CLUSTER_NAME=Shindook
      - DOCKER_NETWORK=docker_hadoop

  datanode2:
    image: akhlakm/hadoop-datanode
    container_name: datanode2
    # restart: always
    environment:
      - CLUSTER_NAME=Shindook
      - DOCKER_NETWORK=docker_hadoop
