version: "3"

services:
  namenode:
    image: akhlakm/hadoop-namenode
    container_name: namenode
    # restart: always
    ports:
      - 9870:9870
      - 9000:9000
    environment:
      - CLUSTER_NAME=Shindook
    networks:
      - bridge

  datanode1:
    image: akhlakm/hadoop-datanode
    container_name: datanode1
    # restart: always
    environment:
      - CLUSTER_NAME=Shindook
    networks:
      - bridge

  datanode2:
    image: akhlakm/hadoop-datanode
    container_name: datanode2
    # restart: always
    environment:
      - CLUSTER_NAME=Shindook
    networks:
      - bridge

  yarn:
    image: akhlakm/hadoop-yarn
    container_name: yarn
    # restart: always
    ports:
      - 9871:8088
    environment:
      - CLUSTER_NAME=Shindook
    networks:
      - bridge

  nodemgr:
    image: akhlakm/hadoop-nodemgr
    container_name: nodemgr
    # restart: always
    ports:
      - 9872:8042
    environment:
      - CLUSTER_NAME=Shindook
    networks:
      - bridge

  histmgr:
    image: akhlakm/hadoop-histmgr
    container_name: histmgr
    # restart: always
    ports:
      - 9873:8188
    environment:
      - CLUSTER_NAME=Shindook
    networks:
      - bridge

networks:
  bridge:
    driver: bridge