version: "3"

services:
  namenode:
    image: akhlakm/hadoop-namenode
    container_name: namenode
    hostname: namenode
    # restart: always
    ports:
      - 9870:9870
      - 9000:9000
      - 2049:2049
      - 4242:4242
    environment:
      - CLUSTER_NAME=Shindook
    networks:
      - bridge

  datanode1:
    image: akhlakm/hadoop-datanode
    container_name: datanode1
    hostname: datanode1
    # restart: always
    ports:
      - 9001:8042
    environment:
      - CLUSTER_NAME=Shindook
    networks:
      - bridge

  datanode2:
    image: akhlakm/hadoop-datanode
    container_name: datanode2
    hostname: datanode2
    # restart: always
    ports:
      - 9002:8042
    environment:
      - CLUSTER_NAME=Shindook
    networks:
      - bridge

  yarn:
    image: akhlakm/hadoop-yarn
    container_name: yarn
    hostname: yarn
    restart: always
    ports:
      - 9871:8088
    environment:
      - CLUSTER_NAME=Shindook
    networks:
      - bridge

  spark:
    image: akhlakm/hadoop-spark
    container_name: spark
    hostname: spark
    # restart: always
    ports:
      - 9888:9888
      - 8080:8080
    environment:
      - CLUSTER_NAME=Shindook
      - SPARK_MASTER_HOST=spark
      - SPARK_MAIN=1
    networks:
      - bridge

networks:
  bridge:
    driver: bridge