build:
	docker build -t akhlakm/hadoop-base ./HadoopBase
	docker build -t akhlakm/hadoop-namenode ./NameNode
	docker build -t akhlakm/hadoop-datanode ./DataNode

run:
	docker compose up -d 

stop:
	docker compose down
