# Load common vars
- name: load common vars
  include_vars: "common.yml"
  tags: always

# Load OS specific vars
- name: load os vars
  include_vars: "{{ ansible_facts['os_family']|lower }}.yml"
  tags: always

- block:
  # RedHat
  - name: dnf update
    dnf: update_cache=yes
  
  - import_tasks: redhat-network.yml

  when: ansible_facts['os_family']|lower == 'redhat'

- block:
  # Debian
  - name: apt update
    apt: update_cache=yes
  
  - import_tasks: debian-network.yml
  
  when: ansible_facts['os_family']|lower == 'debian'

- import_tasks: ssh-setup.yml
- import_tasks: ansible.yml
- import_tasks: akhlak.yml
