- name: static network (redhat)
  template:
    src: static-net-redhat.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ eth_device }}
    owner: root 
    mode: 0644
  when: eth_device is defined
