- name: sshd_config file
  template:
    src: sshd-config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

- meta: flush_handlers

- name: sshd daemon
  service:
    name: "{{ sshd_service }}"
    enabled: yes
    state: started
