- name: user akhlak
  user:
    name: akhlak
    groups: "{{ sudo_group }}"
    state: present
    append: yes

- name: sudoers file akhlak
  copy:
      dest: /etc/sudoers.d/akhlak
      content: "akhlak ALL=(ALL) NOPASSWD: ALL"
      owner: root
      group: root
      mode: 0440

- name: bashrc (debian)
  copy:
    src: bashrc
    dest: /home/akhlak/.bashrc
  when: ansible_facts['os_family']|lower == 'debian'

- name: bashrc (redhat)
  copy:
    src: bashrc
    dest: /etc/profile.d/bashrc.sh
  when: ansible_facts['os_family']|lower == 'redhat'

- block:
  - name: ssh public key
    file:
      path: "/home/akhlak/.ssh/authorized_keys"
      state: file

  rescue:
    - name: no authorized keys
      debug:
        msg: >
          No ssh public key is found in /home/akhlak.
          Please upload a public key for secure access.
