- block:

  - name: docker is installed
    shell: docker --version
    register: cmd_result
    failed_when: "cmd_result.rc != 0"
    changed_when: false

  rescue:

    - name: download get-docker
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: 0744

    - name: execute get-docker
      shell: /tmp/get-docker.sh > get-docker.log

    - name: docker is installed
      shell: docker --version
      register: cmd_result
      failed_when: "cmd_result.rc != 0"

    - name: docker group exists
      group:
        name: docker
        state: present

    - name: akhlak a member of the docker group 
      user:
        name: akhlak
        groups: docker
        append: yes

    - name: ansible a member of the docker group 
      user:
        name: ansible
        groups: docker
        append: yes

- block:
  - name: docker service enabled
    service:
      name: docker
      enabled: yes

  - name: docker service started
    service:
      name: docker
      state: started

  rescue:
    - name: docker service error
      debug:
        msg: |
          Docker service does not seem to be running.
          Please check manually. 

# For ansible docker_container module
- block:
    - name: pip installed
      package:
        name: python3-pip
        state: present

    - name: docker SDK installed
      pip:
        name: docker

# Test the hello world container
- block:
    - name: docker hello world
      docker_container:
        name: helloworld
        image: hello-world
        state: started

