- name: container facts
  set_fact:
    containerName: "mfsMeta"
    containerHostname: "{{ inventory_hostname }}"
    containerHostIP: "{{ ansible_host }}"
    containerImage: akhlakm/mfsmeta
    dockerDirectory: MetaLogger

- name: metadata directory
  file:
    path: /root/mfsMeta
    state: directory

- block:

    - name: metalogger running 
      shell: "docker inspect -f '{{ '{{' }} .State.Running {{ '}}' }}' {{ containerName }}"
      register: cmd
      failed_when: "(cmd.rc != 0) or (cmd.stdout == 'false')"
      changed_when: false

  rescue:

    - name: copy dockerfiles
      copy:
        src: "{{ dockerDirectory }}"
        dest: /tmp/
        mode: 0744

    - name: copy config template
      template:
        src: mfsmetalogger.cfg
        dest: "/tmp/{{ dockerDirectory }}/mfsmetalogger.cfg"
        owner: root
        mode: 0744

    - name: copy host /etc/hosts to container
      # container entrypoint will add these hosts manually
      shell: "cp -f /etc/hosts /tmp/{{ dockerDirectory }}/etc_hosts"

    - name: remove old container
      shell: "docker rm {{ containerName }}"
      ignore_errors: true

    - name: docker build
      shell:
        cmd: "docker build -t {{ containerImage }} {{ dockerDirectory }}"
        chdir: /tmp
      register: cmd_result
      failed_when: "cmd_result.rc != 0"

    - name: docker run
      shell:
        cmd: >
          docker run -td
          -v /root/mfsMeta:/var/lib/mfs
          --hostname="{{ containerHostname }}"
          --name="{{ containerName }}"
          "{{ containerImage }}"

      register: cmd_result
      failed_when: "cmd_result.rc != 0"
