- block:
  - import_tasks: check-installation.yml

- name: mfsmaster not localhost
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1     mfsmaster"
    state: absent
  when: mfsmain != inventory_hostname

- block:
  - include_tasks: check-mfsmain.yml
  when: mfsmain == inventory_hostname

- block:
  - include_tasks: check-mfschunk.yml
  when: mfschunk == true
  tags: chunk
