- name: host IP address set
  fail:
    msg: >
      Please define IP address and name for each host.
      Set ansible_host variables in the hosts file.
  when: inventory_hostname == ansible_host

- block:
  - import_tasks: check-installation.yml

- name: mfsmaster not localhost
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1     mfsmaster"
    state: absent
  when: mfsmain != inventory_hostname

- block:
    - include_tasks: check-mfsmain.yml
  when: mfsmain == inventory_hostname

- block:

    # Run a chunkserver for each mount points
    - name: Check chunkserver
      include_tasks: docker-mfschunk.yml
      loop: "{{ mfschunkmounts | list }}"

  when: mfschunk == true


- block:

    # Run a meta logger in each chunk host
    - name: Check MetaLogger
      include_tasks: docker-mfsmeta.yml
      when: mfsmain != inventory_hostname

  when: mfschunk == true
